name: ZCS CI/CD Pipeline

on:
  push:
    branches: [ main, develop, 'feature/**', 'release/**' ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * *'  # Daily security scans

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Define reusable workflow configurations
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # - name: InitializeCodeQL
      #   uses: github/codeql-action/init@v2
      #   with:
      #     languages: python,javascript
      
      # - name: CodeQL Analysis - SAST
      #   uses: github/codeql-action/analyze@v2
      #   with: 
      #     output: ../results
      #     upload: always
      #     cleanup-level: brutal
      #     skip-queries: false
      #     upload-database: true
      #     wait-for-processing: true
      
      # - name: Dependency Security Scan
      #   uses: snyk/actions/python@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
      # - name: Container Security Scan - File System
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'fs'
      #     format: 'sarif'
      #     output: 'trivy-results-fs.sarif'

      # - name: Container Security Scan - Configuration
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'config'
      #     format: 'sarif'
      #     output: 'trivy-results-config.sarif'

  code-quality:
    name: Code Quality
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: 'pip'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytest pytest-cov pytest-xdist pytest-html black isort flake8 mypy
          pip install -r src/azurefunctions/mymdnotes/requirements.txt
          npm ci --prefix src/frontends/pdfapprover
      # pip install -r requirements-dev.txt

      - name: Code Style Check
        continue-on-error: true
        run: |
          black --check .
          isort --check-only .
          flake8 .
          npm run lint --prefix src/frontends/pdfapprover

      - name: Type Check
        continue-on-error: true
        run: |
          mypy src/
          npm run type-check --prefix src/frontends/pdfapprover
    
  unit-test:
    name: Unit Testing
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      # Step 4: Run tests with pytest
      - name: Run Unit Tests
        env:
          PYTHONPATH: src  # Add src to PYTHONPATH
        run: |
          pytest tests/ --cov=src --cov-report=xml --junitxml=test-results.xml
        continue-on-error: true  # Continue even if this step fails

      # Step 5: Upload test results (optional)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml

      - name: Start Frontend
        # working-directory: ../src/frontends/pdfapprover  # Adjust to correct path
        run: |
          npm run dev -- --host&
          sleep 10  # Wait for the server to start
        # npm install
    
  selenium-test:
    name: Selenium Test Automation
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Run Selenium Tests
        continue-on-error: true  # Continue even if this step fails
        run: |
          pytest tests/selenium_tests/
    
  sonarqube-analysis:
    name: SonarQube Analysis
    needs: selenium-test
    runs-on: ubuntu-latest
    steps:
    # Step 6: Run SonarQube Analysis
    - name: Run SonarQube Analysis
      uses: sonarsource/sonarqube-scan-action@master
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
          args: >
              -Dsonar.projectKey=ZionAIMedFlow-v2
              -Dsonar.organization=ZCS
              -Dsonar.sources=.
              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              -Dsonar.python.coverage.reportPaths=coverage.xml

      # Optional: Quality Gate Check
      # Uncomment this section if you want the job to fail when the SonarQube Quality Gate fails
      # - name: SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  smoke-test:
    name: Smoke Testing
    needs: sonarqube-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Soaham - Testing with Smoke Test File 
      - name: Run Smoke Tests
        env:
          TEST_RESULT: 1  # Control test outcome
        run: |
          pwd
          chmod +x ./scripts/smoke-tests.sh
          ./scripts/smoke-tests.sh ${{ steps.deploy.outputs.url }}
  
  performance-test:
    name: Performance Testing
    needs: smoke-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run k6 Load Tests
        uses: grafana/k6-action@v0.2.0
        env:
          TARGET_URL: ${{ needs.deploy-dev.outputs.url }}
        with:
          filename: performance/load-tests.js
          flags: --vus 10 --duration 30s

      - name: Upload Performance Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: performance/results.json
      
  notify:
    name: Notify Status
    # needs: performance-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send Teams Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
          title: Deployment Status
          summary: |
            The deployment for the repository `${{ github.repository }}` has completed.
            - **Branch**: `${{ github.ref_name }}`
            - **Commit**: `${{ github.sha }}`
            - **Actor**: `${{ github.actor }}`
          text: |
            The deployment process has finished. Please check the details below:
            - **Repository**: `${{ github.repository }}`
            - **Branch**: `${{ github.ref_name }}`
            - **Commit**: `${{ github.sha }}`
            - **Actor**: `${{ github.actor }}`
            - **Workflow**: `${{ github.workflow }}`
            - **Job**: `${{ github.job }}`
            - **Run ID**: `${{ github.run_id }}`
            - **Run Number**: `${{ github.run_number }}`

      - name: Send JIRA Notification
        run: |
          AUTH=$(echo -n "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }}" | base64)
          echo "Authorization: Basic $AUTH"
          JSON_PAYLOAD=$(jq -n --arg repo "${{ github.repository }}" --arg branch "${{ github.ref_name }}" --arg commit "${{ github.sha }}" --arg actor "${{ github.actor }}" --arg workflow "${{ github.workflow }}" --arg job "${{ github.job }}" --arg run_id "${{ github.run_id }}" --arg run_number "${{ github.run_number }}" '{
            fields: {
              project: {
                key: "ZMED"
              },
          summary: "Deployment Status",
          description: "The deployment for the repository \($repo) has completed.\n\n- **Branch**: \($branch)\n- **Commit**: \($commit)\n- **Actor**: \($actor)\n- **Workflow**: \($workflow)\n- **Job**: \($job)\n- **Run ID**: \($run_id)\n- **Run Number**: \($run_number)",
              issuetype: {
                name: "Task"
              }
            }
          }')
          echo "JSON Payload: $JSON_PAYLOAD"
          curl -v -X POST -H "Authorization: Basic $AUTH" \
          -H "Content-Type: application/json" \
          --data "$JSON_PAYLOAD" \
          https://zionclouds.atlassian.net/rest/api/2/issue/
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}